# Generated by Django 4.2 on 2023-05-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0007_auto_20220307_2004"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videos_post",
            name="compressed_format",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="videos_post",
            name="forging_method",
            field=models.CharField(default="", max_length=200),
        ),
    ]
